#!/bin/sh

# bash script to set environment for GNU Fortran Compiler 14.0 
#

gfortran_prefix=/opt/homebrew
##gfortran_prefix=/opt/gcc-12.2.0

softfloat_prefix=$HOME/aarch64

PATH=$gfortran_prefix/bin:$PATH
export DYLD_LIBRARY_PATH=$gfortran_prefix/lib

###libs="-Wl,--rpath,$gfortran_prefix/lib"
libs="-rpath $gfortran_prefix/lib -L$gfortran_prefix/lib"

# stack size 256MB
###libs="$libs -Wl,-stack_size,0x10000000"
# stack size 512MB
libs="$libs -Wl,-stack_size,0x20000000"
# stack size 1024MB
###libs="$libs -Wl,-stack_size,0x40000000"
# stack size 2048MB
###libs="$libs -Wl,-stack_size,0x80000000"
# stack size 4096MB
###libs="-Wl,-stack_size,0x100000000"

args="-std=legacy -march=native"
###args="-std=legacy -fmax-stack-var-size=65536"
###args="-std=legacy -fmax-stack-var-size=131072"
###args="-std=legacy -fmax-stack-var-size=262154"

###libs="$libs -Wl,-no_warn_duplicate_libraries"

if_linker=1
if_softfloat_quad=0
if_static=0

while
  test -n "$1"
do
#  echo "$1 "
  case $1 in
  '-c')
    args="$args -c"
    if_linker=0
  ;;
  '-shared')
      args="$args $1"
      libs=""
      if_linker=0
  ;;
  '-dynamiclib')
      args="$args $1"
      libs=""
      if_linker=0
  ;;
  '-static')
    args="$args -static"
    if_static=1
  ;;
  '-fast')
###    args="$args -O3 -fno-inline -fautomatic -funroll-loops -march=native -ffast-math"
    args="$args -O3 -march=native"
###    args="$args -O3 -fno-inline -fautomatic -funroll-loops -march=native"
###    args="$args -O3 -fno-inline -fautomatic -march=corei7 -ffast-math"
###    args="$args -O3 -fno-inline -fautomatic -funroll-loops -march=corei7"
###    args="$args -O3 -fno-inline -fautomatic"
###    args="$args -O2 -fno-whole-file -fno-inline -fautomatic"
###    args="$args -O3 -fno-whole-file -fno-inline -fautomatic"
  ;;
  '-i8')
    args="$args -finteger-4-integer-8"
###    args="$args -fdefault-integer-8"
  ;;
  '-r8')
    args="$args -freal-4-real-8"
###    args="$args -fdefault-real-8 -fdefault-double-8"
  ;;
  '-r10')
    args="$args -freal-4-real-10"
  ;;
  '-r16')
    args="$args -freal-4-real-16"
  ;;
  '-As')
    args="$args -freal-8-real-4"
  ;;
  '-Ad')
    args="$args -freal-4-real-8"
  ;;
  '-Ae')
    args="$args -freal-8-real-10"
  ;;
  '-Aq')
    args="$args -freal-8-real-16"
    if_softfloat_quad=1
  ;;
  '-Aq-')
    args="$args -freal-8-real-16"
    if_softfloat_quad=0
  ;;
  '-CcII8')
    args="$args -fdefault-integer-8"
  ;;
  '-CcI4I8')
    args="$args -finteger-4-integer-8"
  ;;
  '-CcRR8')
    args="$args -fdefault-real-8 -fdefault-double-8"
  ;;
  '-CcR4R8')
    args="$args -freal-4-real-8"
  ;;
  '-init-real')
    args="$args -finit-real=nan"
  ;;
  '-a')
    args="$args -frecursive"
  ;;
  *)
    args="$args $1"
  ;;
  esac
  shift
done

### echo $args

if [ "$if_softfloat_quad" = "1" ]; then
###   libs="$libs -rpath $softfloat_prefix/lib"
   libs="$libs $softfloat_prefix/lib/softfloat_quad.o"
   libs="$libs -L $softfloat_prefix/lib"
   libs="$libs $softfloat_prefix/lib/libsoftfloat.a" 
fi

if [ "$if_static" = "1" ]; then
   libs="$libs"
###   libs="$libs -mcmodel=medium"
fi

if [ "$if_linker" = "1" ]; then
   args="$args $libs"
fi


###/usr/local/bin/gfortran-7 $args
MACOSX_DEPLOYMENT_TARGET=15.0 gfortran-15 $args
###gfortran -static $args
###gfortran -static -mcmodel=medium $args

