#
#  Generate Matlab/Octave MEX files
#
#  gfortran > 4.4.0 is strongly recommended
#

PROJECT = libid
MEX_GATEWAY = $(PROJECT)


###TARGET=octave-linux
TARGET=octave-linux-openmp

###TARGET=octave-linux-intel
###TARGET=octave-linux-intel-openmp

###TARGET=matlab-linux-a64
###TARGET=matlab-linux-a64-openmp

###TARGET=matlab-maci
###TARGET=matlab-maci-openmp
###TARGET=matlab-maci64
###TARGET=matlab-maci64-openmp

###TARGET=matlab-windows-w32
###TARGET=matlab-windows-w32-openmp
###TARGET=matlab-windows-w64
###TARGET=matlab-windows-w64-openmp

include mwrap.inc



.f.$(OBJSUF):
	$(MEX_FC) $(MEX_FLAGS) -c $(FFLAGS) $<

.c.$(OBJSUF):
	$(MEX_CC) $(MEX_FLAGS) -c $(CFLAGS) $<

.SUFFIXES: .$(OBJSUF) .f .c


# SOURCE FILE LIST
#
vpath %.f .:..:../src

FSRCS = id_rand.f id_rtrans.f idd_frm.f idd_house.f idd_id.f idd_id2svd.f \
        idd_qrpiv.f idd_sfft.f idd_snorm.f idd_svd.f iddp_aid.f iddp_asvd.f \
        iddp_rid.f iddp_rsvd.f iddr_aid.f iddr_asvd.f iddr_rid.f iddr_rsvd.f \
        idz_frm.f idz_house.f idz_id.f idz_id2svd.f idz_qrpiv.f idz_sfft.f \
	idz_snorm.f idz_svd.f idzp_aid.f idzp_asvd.f idzp_rid.f idzp_rsvd.f \
        idzr_aid.f idzr_asvd.f idzr_rid.f idzr_rsvd.f

FSRCS += dfft.f prini.f 

LIBS = -llapack -lblas

#
# object files list
OBJS    = $(FSRCS:.f=.$(OBJSUF)) 
#

all: $(OBJS) 
	$(MW) $(MWFLAGS) $(MEX_GATEWAY) -mb $(PROJECT).mw
	$(MW) $(MWFLAGS) $(MEX_GATEWAY) -c $(MEX_GATEWAY).c $(PROJECT).mw
	$(MEX) -v $(MEX_FLAGS) $(MEX_LINK) $(MEX_GATEWAY).c $(OBJS) $(MEX_LIBS) $(LIBS)

doc:
	$(MW) $(MWFLAGS) $(MEX_GATEWAY) -mb $(PROJECT).mw

#
clean: 
	rm -f $(OBJS)
# 
list: $(FSRCS)
	echo $^
#
distclean: 
	rm -f $(OBJS) int2 fort.* *.o

